# Generated by Django 5.2 on 2025-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rssitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
