# Generated by Django 5.2 on 2025-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_rssitem_image_url_rssitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
